### ISSUE TITLE
RealtimeOrderBookSubscription fails

### ISSUE THREAD

**Issue by rsgabriel** [vslee/CoinbaseExchange.NET#1]
I ran into an issue where matches stopped coming through the RealtimeOrderBookSubscription, I am using the following code:

        private void InitializeFeed()
        {
            Task.Run(async () =>
            {
                try
                {
                    feed = new RealtimeOrderBookClient(Currency + "-USD", authContainer);

                    await feed.RealtimeOrderBookSubscription.SubscribeAsync(true);

                    feed.RealtimeOrderBookSubscription.RealtimeMatch += (object sender, RealtimeMatch e) =>
                    {
                        lock (Trades)
                        {
                            Trades.Add(e);
                        }
                        Console.WriteLine("[" + DateTime.Now.ToLongTimeString() + "] Trade Price: [" + e.Price + "] Size: [" + e.Size + "]");
                    };

                    feed.RealtimeOrderBookSubscription.ConnectionClosed += (sender, eventArgs) =>
                    {
                        LogError("ConnectionClosed");
                        //InitializeFeed();
                    };

                    feed.RealtimeOrderBookSubscription.RealtimeStreamError += (sender, error) =>
                    {
                        LogError("RealtimeStreamError");
                        //InitializeFeed();
                    };
                }
                catch (Exception e)
                {
                    LogError(e.Message + " | " + e.StackTrace);
                }

            }).GetAwaiter().GetResult();
        }

As-is above, the feed seems to stop providing trades after ~24-48 hours. I tried re-initializing everything in the ConnectionClosed and RealtimeStreamError events, however this resulted in an OutOfMemory exception.

Is there a suggested best practice for how to handle the ConnectionClosed or RealtimeStreamError events?

What is the suggested way to keep the trades rolling in indefinitely?

**Comment by rsgabriel** [comment]
Exception information about when this happens:

8/14/2017 2:45:20 PM|Fatal|<>c__DisplayClass17.<startReceiving>b__16|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                              at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                              at WebSocketSharp.WebSocketFrame.<>c__DisplayClassa.<readHeaderAsync>b__9(Byte[] bytes)
                              at WebSocketSharp.Ext.<>c__DisplayClass9.<ReadBytesAsync>b__8(IAsyncResult ar)
8/14/2017 2:45:20 PM|Fatal|WebSocket.connect|WebSocketSharp.WebSocketException:
An error has occurred during a TLS handshake. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
                              --- End of inner exception stack trace ---
                              at System.Net.Security.SslState.StartSendAuthReset1Signal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
                              at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                              at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                              at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
                              at WebSocketSharp.WebSocket.setClientStream()
                              
							  --- End of inner exception stack trace ---
                              at WebSocketSharp.WebSocket.setClientStream()
                              at WebSocketSharp.WebSocket.doHandshake()
                              at WebSocketSharp.WebSocket.connect()
							  
8/14/2017 2:45:21 PM|Error|WebSocket.Send|This operation isn't available in: closed

**Comment by rsgabriel** [comment]
I've discovered three separate issues related to this:

1) The websocket can experience an OutOfMemory Exception
2) The above mentioned Stream read issue
3) Trades simply stop coming in.

**Comment by vslee** [comment]
Should be fixed now 2baf518
